"""Initial migration

Revision ID: c104c57a24b8
Revises: 
Create Date: 2025-12-10 20:45:03.584490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c104c57a24b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('robotics_project_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=False),
    sa.Column('project_title', sa.String(length=200), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('problem_solved', sa.Text(), nullable=True),
    sa.Column('components', sa.Text(), nullable=True),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('project_goal', sa.Text(), nullable=True),
    sa.Column('help_needed', sa.Text(), nullable=True),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('uploaded_files', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('project_link', sa.String(length=500), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['student_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['student_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_order')
    op.drop_table('product')
    op.drop_table('product_cart_item')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('featured')

    op.create_table('product_cart_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('short_description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('product_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sku', sa.VARCHAR(length=50), nullable=True),
    sa.Column('stock_quantity', sa.INTEGER(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('featured', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('product_order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('shipping_address', sa.TEXT(), nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('ordered_at', sa.DATETIME(), nullable=True),
    sa.Column('shipped_at', sa.DATETIME(), nullable=True),
    sa.Column('delivered_at', sa.DATETIME(), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('customer_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('customer_address', sa.TEXT(), nullable=True),
    sa.Column('payment_proof', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('project_like')
    op.drop_table('project_comment')
    op.drop_table('student_project')
    op.drop_table('robotics_project_submission')
    op.drop_table('password_reset_token')
    # ### end Alembic commands ###
