from .main import bp as main
from .auth import bp as auth
from .projects import bp as projects
from .materials import bp as materials
from .admin import bp as admin
from .store import bp as store
from .uploads import bp as uploads
from .integrations import bp as integrations
from .student_projects import bp as student_projects
from .file_uploads import bp as file_uploads
from .health import bp as health
